# Generated by Django 4.1.1 on 2022-09-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_produtos', '0003_alter_transacao_data_alter_transacao_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
