# Generated by Django 4.1.1 on 2022-09-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_produtos', '0004_alter_transacao_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transacao',
            new_name='produto',
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name_plural': 'Produtos'},
        ),
    ]
