# Generated by Django 4.1.1 on 2022-09-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_produtos', '0005_rename_transacao_produto_alter_produto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='nome',
        ),
    ]
